<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20486" started-at="2018-05-28T20:45:10Z" finished-at="2018-05-28T20:45:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20486" started-at="2018-05-28T20:45:10Z" finished-at="2018-05-28T20:45:31Z">
      <class name="automation.test.roi4cio.homepage.TestLoginPage">
        <test-method status="PASS" signature="openHomePage()[pri:0, instance:automation.test.roi4cio.homepage.TestLoginPage@885e7ff]" name="openHomePage" is-config="true" duration-ms="12773" started-at="2018-05-28T23:45:10Z" finished-at="2018-05-28T23:45:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openHomePage -->
        <test-method status="FAIL" signature="testLoggedUserAsUser()[pri:1, instance:automation.test.roi4cio.homepage.TestLoginPage@885e7ff]" name="testLoggedUserAsUser" duration-ms="5064" started-at="2018-05-28T23:45:23Z" finished-at="2018-05-28T23:45:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
User :user@test.com
 should be logged in user company expected [Пользователь1] but found [Пользователь]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
User :user@test.com
 should be logged in user company expected [Пользователь1] but found [Пользователь]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at automation.test.roi4cio.homepage.TestLoginPage.testLoggedUserAsUser(TestLoginPage.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoggedUserAsUser -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:automation.test.roi4cio.homepage.TestLoginPage@885e7ff]" name="tearDown" is-config="true" duration-ms="2544" started-at="2018-05-28T23:45:28Z" finished-at="2018-05-28T23:45:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automation.test.roi4cio.homepage.TestLoginPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
